version: '3.1'

services:
  backend:
    build: .
    ports: 
      - 5000:80
    links:
      - database
  database:
    image: postgres
    restart: always
    
    environment:
      POSTGRES_PASSWORD: Kaliakakya